### ISSUE TITLE
Save VolunteerForm data in local storage

### ISSUE THREAD

**Issue by jensren** [reach4help/covidhelphub-frontend#11]
**What**: save `VolunteerFormComponent` submission data in local storage

**Why**: temporary implementation before GraphQL backend is set up to accept form submission data

**Implementation details**: similar to `ProgramService.ts` and `RequestService.ts`. Create a new `VolunteerService.ts` file.

Requirements:
- On form submit, form data is saved to local storage
- Multiple submissions can be saved to local storage without removing previous submissions

There is no need to make this too sophisticated, since saving to local storage is a temporary implementation until GraphQL is read to accept form submissions.

**Comment by pratikmdhr** [comment]
I'd like to work on this

**Comment by jensren** [comment]
Hey @pratikmdhr, we recently decided to mock the backend instead so I don't think this issue is relevant anymore. Thanks for your interest in the project though, and let me know if you'd like to work on something else!

**Comment by pratikmdhr** [comment]
> Hey @pratikmdhr, we recently decided to mock the backend instead so I don't think this issue is relevant anymore. Thanks for your interest in the project though, and let me know if you'd like to work on something else!

sure, i will look at other issues and will let you know.. thanks!
