### ISSUE TITLE
Add submitted page for VolunteerFormComponent

### ISSUE THREAD

**Issue by jensren** [reach4help/covidhelphub-frontend#12]
**What**: add a new page for after the user submits the volunteer form, saying 'Form submitted' or something similar

**Why**: currently submitting the volunteer form does not trigger any page change, which is confusing

**Implementation details**: use the router to switch to a new page and display the text, by doing `history.push(<new route>)` and adding the new route to `App.tsx`. If you are not familiar with React routers, you can take a look at the [docs](https://reactrouter.com/docs/en/v6).

Requirements:
- If the user presses back after submitting, the user should return to the form page
- The page should only switch if the form submission was successful (i.e. the user is submitting valid inputs)
- The submitted page has a different route (maybe <form url>/submitted) and on submit the user is sent to this route
- No specific requirements for how the submitted page looks, as long as it seems to match and it is clear the user submitted the form. It would be nice if it looked good and we could reuse it for other submitted forms, but it's also fine if it's just functional

**Comment by praguru14** [comment]
Hi Can I get this assigned to me?

**Comment by jensren** [comment]
Hi, thank you for your interest in our project! I saw that you submitted a PR already. I'll take a look a bit later!
