### ISSUE TITLE
Research React CSS Framework

### ISSUE THREAD

**Issue by jensren** [reach4help/covidhelphub-frontend#20]
We want an easy to use framework so we don't develop everything ourselves, and the look and feel of the app is more standardized

**Comment by ethanstrominger** [comment]
Based on the number of stars and popularity I recommend Bootstrap in combination with React-Table library in combination with.  material-ui also gets mentioned a lot, it has advanced features but I have heard it is complicated to use.

Here are some articles:
- [Top 5 React Table Libraries] (https://blog.logrocket.com/the-top-react-table-libraries-to-use-in-2021/)
  (I don't agree that React is lacking in documentation - maybe the authors did not produce documentation but other people have)
[Column resizing in React Table](https://react-table.tanstack.com/docs/examples/column-resizing)
[Statistics on react table](https://www.npmtrends.com/material-table-vs-material-ui-datatables-vs-react-table-vs-rsuite-table)

**Comment by jensren** [comment]
Shayan's suggestion (copied from Slack to document it here):
For a data table library, here's a neat open source one I found that you could look into: https://grid.glideapps.com/

**Comment by jensren** [comment]
Decided on styled components and SemanticUI
