### ISSUE TITLE
Add Program Stages navbar

### ISSUE THREAD

**Issue by jensren** [reach4help/covidhelphub-frontend#42]
**What**: add the navbar for the program stages, as shown in the green box:

![image](https://user-images.githubusercontent.com/41408654/148313985-09946da2-0ede-4cd6-b3fa-b4a4f3995515.png)

**Why**: we want to have the navbar in place so we can link the pages when we create them.

**How**:
- Add the navbar on the programs page
- Each link in the navbar should link to a new page, e.g. /programs/open
- The navbar links should have a chevron arrow showing which page the user is on, as shown in the Figma design
- The style does not have to match the Figma design perfectly (since the Figma is still a work in progress)
- Styles should be in a `.module.css` - we will be using styled components later, but we don't have that set up yet

**Comment by pratikmdhr** [comment]
I'll work on this
